import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';

const defaultEndPoint = 'https://rickandmortyapi.com/api/character/';

export async function getServerSideProps() {
  const res = await fetch(defaultEndPoint);
  const data = await res.json();

  return {
    props: {
      data
    }
  }
}

export default function Home({ data }) {

  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);
  const [page, upadatePage] = useState({
    ...info,
    current: defaultEndPoint
  });

  const { current } = page;

  useEffect(() => {
    if (current === defaultEndPoint) return;

    async function request() {
      const res = await fetch(current);
      const nextData = await res.json();

      upadatePage({
        current,
        ...nextData.info
      });

      if (!nextData.info?.prev) {
        updateResults(nextData.results);
        return;
      }

      updateResults(prev => {
        return [
          ...prev,
          ...nextData.results
        ]
      });
    }

    request();
  }, [current]);

  function handleLoadMore() {
    upadatePage(prev => {
      return {
        ...prev,
        current: page?.next
      }
    })
  }
  
  function handleOnSubmitSearch(e) {
    e.preventDefault();

    const { currentTarget = {} } = e;
    const fields = Array.from(currentTarget?.elements);
    const fieldQuery = fields.find(field => field.name === 'query');

    const value = fieldQuery.value || '';
    const endpoint = `https://rickandmortyapi.com/api/character/?name=${value}`;

    upadatePage({
      current: endpoint
    });
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Title
        </h1>

        <p className={styles.description}>
          Description
        </p>

        <form className='search' onSubmit={handleOnSubmitSearch}>
          <input name="query" type="search" />
          <button>Search</button>
        </form>

        <ul className={styles.grid}>
          {results.map(result => {
            const { id, name, image, origin} = result;

            return (
              <>
                <li
                  key={id}
                  className={styles.card}
                >
                  <a href="https://nextjs.org/docs">
                    <img src={image} alt={name} />
                    <h2>{name}</h2>
                    <p>
                      <strong>origin: </strong>{origin.name}
                    </p>
                  </a>
                </li>
              </>
            )
          })}
        </ul>
        <p>
          <button onClick={handleLoadMore}>Load more</button>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
