import Head from 'next/head';
import styles from '../../../styles/Home.module.css';

const defaultEndPoint = 'https://rickandmortyapi.com/api/character/';

export async function getServerSideProps({ query }) {
  const { id } = query;
  const res = await fetch(`${defaultEndPoint}/${id}`);
  const data = await res.json();

  return {
    props: {
      data
    }
  }
}

export default function Character({ data }) {

  const { name, image, gender, location, origin, species, status } = data;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          { name }
        </h1>

        <div className={styles.profile}>
          <div className={styles.profileImage}>
            <img src={image} alt={name} />
          </div>

          <div className={styles.profileDetailes}>
            <ul>
              <li>
                <strong>Name: </strong> { name }
              </li>
              <li>
                <strong>Status: </strong> { status }
              </li>
              <li>
                <strong>Gender: </strong> { gender }
              </li>
              <li>
                <strong>Species: </strong> { species }
              </li>
              <li>
                <strong>Location: </strong> { location?.name }
              </li>
              <li>
                <strong>Origin: </strong> { origin?.name }
              </li>
            </ul>
          </div>

        </div>
        
      </main>

    </div>
  )
}
